kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-map-unmap
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - create
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - list
