kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-map-unmap
subjects:
  - kind: ServiceAccount
    name: test-map-unmap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-map-unmap
